### ISSUE TITLE
Enhancement Shaman

### ISSUE THREAD

**Issue by Nighteyez07** [MartijnHols/WoWAnalyzer#120]
## **TODO:**

- [ ] Add talent descriptions
- [x] Add basic shaman spells to SPELLS_SHAMAN.js
- [x] Add equipped Legendaries to Item list

- [ ] Track all applicable buff times
    - [x] Flametongue at least 85%
    - [x] Frostbrand at least 85%, warn if Hailstorm not talented
    - [x] Landslide at least 85% if Boulderfist is talented
    - [ ] Look into what additional buff times should be tracked (T20 2pc and so on)

- [ ] Maelstrom usage and generation
    - [x] Show Maelstrom graph
    - [x] Show all spells that generate Maelstrom
    - [ ] Show all spells that spend Maelstrom

- [ ] Include all important trinkets
- [ ] Tier 19/20 2er 4er DPS

# **Items / Legendaries**

- Vial of Ceaseless Toxins #

- Specter of Betrayal #

- Many more...

**Comment by KappKapp** [comment]
Reigh's suggestions:

- Show Frostbrand uptime in the top section when Hailstorm is talented

- Show Earthen Spike cast efficiency when talent is taken (HIGH PRIO)

- Try to remove Doom Vortex "casts" when displaying casts inside Ascendance in the Procs section

- Fix stat percentages logic

- Make sure a warning or suggestion is added if a large amount of maelstrom is wasted from Rockbiter (100+)

**Comment by Nighteyez07** [comment]
**Added**
- Frostbrand uptime has been added.
- Earthen Spike shows up in Cast Efficiency if talented
- Doom Vortex removed from casted spells list during Ascendance
- Stat percentages were tweaked to correctly warn (was showing Major if efficiency was less than 45%, not 90%)
- Added Rockbiter Maelstrom wastage notice

Still working the Fury of Air issue on the Maelstrom page
